service: screenshots-bot

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  memorySize: 4000
  timeout: 30
  logRetentionInDays: 60
  stackTags:
    Project: puppeteer-bot
    Dev: Sri Praveen
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:*"
      Resource: "*"
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - lambda:InvokeFunction
        - events:PutRule
        - events:PutTargets
        - s3:*
      Resource: "*"
    - Effect: Allow
      Action:
        - sqs:*
      Resource: "*"
  deploymentBucket:
    name: take-screeshots-cp

functions:
  takeScreenshot:
    handler: ./index.handler
    events:
      - http:
          path: /postUrlForScreenshots
          method: post
